#Cortex M3 build folder's SConscript file

Import('env')

srcs = env.Glob('*.c')

cm3_sw = Split('-mcpu=cortex-m3 -mfloat-abi=soft -mthumb')

cm3_env = env.Clone()

cm3_env.Append(CCFLAGS=cm3_sw,CXXFLAGS=cm3_sw,LINKFLAGS=cm3_sw,ASFLAGS=cm3_sw)

cm3_env.StaticLibrary(target='arm_cortexM3l_fixmath',source=srcs)









