#Cortex M0+ build folder's SConscript file

Import('env')

srcs = env.Glob('*.c')

cm0_sw = Split('-mcpu=cortex-m0plus -mfloat-abi=soft -mthumb')

cm0_env = env.Clone()

cm0_env.Append(CCFLAGS=cm0_sw,CXXFLAGS=cm0_sw,LINKFLAGS=cm0_sw,ASFLAGS=cm0_sw)

cm0_env.StaticLibrary(target='arm_cortexM0plusl_fixmath',source=srcs)







